import {OWNER,REPO} from './config.js';
const $=s=>document.querySelector(s), zone='America/New_York';
const issueUrl=`https://github.com/${encodeURIComponent(OWNER)}/${encodeURIComponent(REPO)}/issues/new?template=submit-event.yml`;
$('#submitLink').href=issueUrl;$('#submitTop').href=issueUrl;$('#sourceLink').href=`https://github.com/${encodeURIComponent(OWNER)}/${encodeURIComponent(REPO)}`;
let events=[];
const fmt=new Intl.DateTimeFormat('en-US',{timeZone:zone,weekday:'short',month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'});
function localDate(s){return new Date(`${s}:00-04:00`)} // Used only for sorting; offset does not change relative order of local timestamps.
function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function display(s){let [d,t]=s.split('T');let [y,m,day]=d.split('-').map(Number),[h,min]=t.split(':').map(Number);return new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'numeric',year:'numeric'}).format(new Date(Date.UTC(y,m-1,day)))+' · '+new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit'}).format(new Date(2020,0,1,h,min))}
function utc(s){let guess=Date.parse(s+':00Z');for(let i=0;i<3;i++){let parts=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(guess)).filter(p=>p.type!=='literal').map(p=>[p.type,Number(p.value)]));let actual=Date.UTC(parts.year,parts.month-1,parts.day,parts.hour,parts.minute,parts.second);guess+=Date.parse(s+':00Z')-actual}return new Date(guess)}
const stamp=d=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');
function ics(e){let esc=s=>String(s||'').replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');let content=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Cumberland Events//EN','CALSCALE:GREGORIAN','BEGIN:VEVENT',`UID:${esc(e.id)}@cumberland-events.local`,`DTSTAMP:${stamp(new Date())}`,`DTSTART:${stamp(utc(e.start))}`,`DTEND:${stamp(utc(e.end))}`,`SUMMARY:${esc(e.title)}`,`DESCRIPTION:${esc(e.description)}`,`LOCATION:${esc(`${e.venue}, ${e.town}, PA`)}`,`URL:${e.url}`,'END:VEVENT','END:VCALENDAR'].join('\r\n')+'\r\n';let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type:'text/calendar;charset=utf-8'}));a.download=`event-${e.id}.ics`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),30000)}
function calendar(e){let start=stamp(utc(e.start)),end=stamp(utc(e.end));return 'https://calendar.google.com/calendar/render?'+new URLSearchParams({action:'TEMPLATE',text:e.title,dates:`${start}/${end}`,details:`${e.description}\n${e.url}`,location:`${e.venue}, ${e.town}, PA`})}
function outlook(e){return 'https://outlook.live.com/calendar/0/deeplink/compose?'+new URLSearchParams({path:'/calendar/action/compose',rru:'addevent',subject:e.title,startdt:utc(e.start).toISOString(),enddt:utc(e.end).toISOString(),body:`${e.description}\n${e.url}`,location:`${e.venue}, ${e.town}, PA`})}
function option(sel,values){for(let value of [...new Set(values)].sort()){let o=document.createElement('option');o.value=o.textContent=value;sel.append(o)}}
function render(){let q=$('#search').value.trim().toLowerCase(),when=$('#when').value,cat=$('#category').value,town=$('#town').value,day=today(),items=events.filter(e=>(when==='all'||(when==='upcoming'?e.end.slice(0,10)>=day:e.end.slice(0,10)<day))&&(!cat||e.category===cat)&&(!town||e.town===town)&&`${e.title} ${e.venue} ${e.town} ${e.description}`.toLowerCase().includes(q));$('#count').textContent=`${items.length} event${items.length===1?'':'s'}`;let grid=$('#grid');grid.replaceChildren();if(!items.length){let p=document.createElement('p');p.className='empty';p.textContent='No events match these filters yet. Have one to share? Submit an event below.';grid.append(p);return}for(let e of items){let card=document.createElement('article');card.className='card';let tag=document.createElement('span');tag.className='tag';tag.textContent=e.category;let h=document.createElement('h3');h.textContent=e.title;let date=document.createElement('p');date.className='details';date.textContent='◷ '+display(e.start);let place=document.createElement('p');place.className='details';place.textContent=`⌖ ${e.venue}, ${e.town}`;let desc=document.createElement('p');desc.className='desc';desc.textContent=e.description;let links=document.createElement('div');links.className='links';for(let [label,href] of [['Details ↗',e.url],['Google Calendar ↗',calendar(e)],['Outlook ↗',outlook(e)]]){let a=document.createElement('a');a.textContent=label;a.href=href;a.target='_blank';a.rel='noopener noreferrer';links.append(a)}let btn=document.createElement('button');btn.type='button';btn.className='outline';btn.textContent='Download .ics';btn.addEventListener('click',()=>ics(e));links.append(btn);card.append(tag,h,date,place,desc,links);grid.append(card)}}
try{let response=await fetch('./data/events.json',{cache:'no-store'});if(!response.ok)throw Error('Unable to load events');let data=await response.json();events=(Array.isArray(data)?data:[]).filter(e=>e&&e.id&&e.title&&e.start&&e.end&&e.url).sort((a,b)=>localDate(a.start)-localDate(b.start));option($('#category'),events.map(e=>e.category));option($('#town'),events.map(e=>e.town));render()}catch(err){$('#status').textContent='Events are temporarily unavailable. Please try again later.'}for(let id of ['search','when','category','town'])$('#'+id).addEventListener(id==='search'?'input':'change',render);
